import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";

const JetBrains = Poppins({
  subsets: ['latin'],
  weight: ['400', '700','300','500'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${JetBrains.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
